In [2]:
# .venv\Scripts\activate

import pyreadstat
import numpy as np
from scipy import stats
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor
from scipy.spatial.distance import mahalanobis

In [3]:
# Load the SAS dataset
df, meta = pyreadstat.read_sas7bdat(r"C:\Users\mithu\Documents\MEGA\VUW\Summer Research Project\Datasets\PISA 2015\PUF_SAS_COMBINED_CMB_STU_QQQ\cy6_ms_cmb_stu_qqq.sas7bdat")

In [4]:
# Optional: inspect data and metadata
print(df.head())

   CNTRYID  CNT  CNTSCHID  CNTSTUID   CYC  NatCen  Region  STRATUM SUBNATIO  \
0      8.0  ALB  800001.0  803627.0  06MS  000800   800.0  ALB0005  0080000
1      8.0  ALB  800001.0  800454.0  06MS  000800   800.0  ALB0005  0080000
2      8.0  ALB  800001.0  800893.0  06MS  000800   800.0  ALB0005  0080000
3      8.0  ALB  800001.0  804180.0  06MS  000800   800.0  ALB0005  0080000
4      8.0  ALB  800001.0  800491.0  06MS  000800   800.0  ALB0005  0080000

   OECD  ...  PV3SSES  PV4SSES  PV5SSES  PV6SSES  PV7SSES  PV8SSES  PV9SSES  \
0   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN      NaN
1   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN      NaN
2   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN      NaN
3   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN      NaN
4   0.0  ...      NaN      NaN      NaN      NaN      NaN      NaN      NaN

   PV10SSES  SENWT           VER_DAT
0       NaN  2.181  15NOV16:10:10:29
1       NaN  2.181  15NOV16:10:10:29
2       NaN  2.181  15NOV16:10:10:29
3       NaN  2.181  15NOV16:10:10:29
4       NaN  2.181  15NOV16:10:10:29

[5 rows x 921 columns]

In [5]:
print(meta.column_names)

['CNTRYID', 'CNT', 'CNTSCHID', 'CNTSTUID', 'CYC', 'NatCen', 'Region', 'STRATUM', 'SUBNATIO', 'OECD', 'ADMINMODE', 'Option_CPS', 'Option_FL', 'Option_ICTQ', 'Option_ECQ', 'Option_PQ', 'Option_TQ', 'Option_UH', 'Option_Read', 'Option_Math', 'LANGTEST_QQQ', 'LANGTEST_COG', 'LANGTEST_PAQ', 'CBASCI', 'BOOKID', 'ST001D01T', 'ST003D02T', 'ST003D03T', 'ST004D01T', 'ST005Q01TA', 'ST006Q01TA', 'ST006Q02TA', 'ST006Q03TA', 'ST006Q04TA', 'ST007Q01TA', 'ST008Q01TA', 'ST008Q02TA', 'ST008Q03TA', 'ST008Q04TA', 'ST011Q01TA', 'ST011Q02TA', 'ST011Q03TA', 'ST011Q04TA', 'ST011Q05TA', 'ST011Q06TA', 'ST011Q07TA', 'ST011Q08TA', 'ST011Q09TA', 'ST011Q10TA', 'ST011Q11TA', 'ST011Q12TA', 'ST011Q16NA', 'ST011D17TA', 'ST011D18TA', 'ST011D19TA', 'ST012Q01TA', 'ST012Q02TA', 'ST012Q03TA', 'ST012Q05NA', 'ST012Q06NA', 'ST012Q07NA', 'ST012Q08NA', 'ST012Q09NA', 'ST013Q01TA', 'ST123Q01NA', 'ST123Q02NA', 'ST123Q03NA', 'ST123Q04NA', 'ST019AQ01T', 'ST019BQ01T', 'ST019CQ01T', 'ST021Q01TA', 'ST022Q01TA', 'ST124Q01TA', 'ST125Q01NA', 'ST126Q01TA', 'ST127Q01TA', 'ST127Q02TA', 'ST127Q03TA', 'ST111Q01TA', 'ST118Q01NA', 'ST118Q02NA', 'ST118Q03NA', 'ST118Q04NA', 'ST118Q05NA', 'ST119Q01NA', 'ST119Q02NA', 'ST119Q03NA', 'ST119Q04NA', 'ST119Q05NA', 'ST121Q01NA', 'ST121Q02NA', 'ST121Q03NA', 'ST082Q01NA', 'ST082Q02NA', 'ST082Q03NA', 'ST082Q08NA', 'ST082Q09NA', 'ST082Q12NA', 'ST082Q13NA', 'ST082Q14NA', 'ST034Q01TA', 'ST034Q02TA', 'ST034Q03TA', 'ST034Q04TA', 'ST034Q05TA', 'ST034Q06TA', 'ST039Q01NA', 'ST039Q02NA', 'ST039Q03NA', 'ST039Q04NA', 'ST039Q05NA', 'ST039Q06NA', 'ST059Q01TA', 'ST059Q02TA', 'ST059Q03TA', 'ST060Q01NA', 'ST061Q01NA', 'ST062Q01TA', 'ST062Q02TA', 'ST062Q03TA', 'ST071Q01NA', 'ST071Q02NA', 'ST071Q03NA', 'ST071Q04NA', 'ST071Q05NA', 'ST031Q01NA', 'ST032Q01NA', 'ST032Q02NA', 'ST063Q01NA', 'ST063Q01NB', 'ST063Q02NA', 'ST063Q02NB', 'ST063Q03NA', 'ST063Q03NB', 'ST063Q04NA', 'ST063Q04NB', 'ST063Q05NA', 'ST063Q05NB', 'ST063Q06NA', 'ST063Q06NB', 'ST064Q01NA', 'ST064Q02NA', 'ST064Q03NA', 'ST097Q01TA', 'ST097Q02TA', 'ST097Q03TA', 'ST097Q04TA', 'ST097Q05TA', 'ST098Q01TA', 'ST098Q02TA', 'ST098Q03NA', 'ST098Q05TA', 'ST098Q06TA', 'ST098Q07TA', 'ST098Q08NA', 'ST098Q09TA', 'ST098Q10NA', 'ST100Q01TA', 'ST100Q02TA', 'ST100Q03TA', 'ST100Q04TA', 'ST100Q05TA', 'ST103Q01NA', 'ST103Q03NA', 'ST103Q08NA', 'ST103Q11NA', 'ST104Q01NA', 'ST104Q02NA', 'ST104Q03NA', 'ST104Q04NA', 'ST104Q05NA', 'ST107Q01NA', 'ST107Q02NA', 'ST107Q03NA', 'ST092Q01TA', 'ST092Q02TA', 'ST092Q04TA', 'ST092Q05TA', 'ST092Q06NA', 'ST092Q08NA', 'ST092Q09NA', 'ST093Q01TA', 'ST093Q03TA', 'ST093Q04TA', 'ST093Q05TA', 'ST093Q06TA', 'ST093Q07NA', 'ST093Q08NA', 'ST094Q01NA', 'ST094Q02NA', 'ST094Q03NA', 'ST094Q04NA', 'ST094Q05NA', 'ST095Q04NA', 'ST095Q07NA', 'ST095Q08NA', 'ST095Q13NA', 'ST095Q15NA', 'ST113Q01TA', 'ST113Q02TA', 'ST113Q03TA', 'ST113Q04TA', 'ST129Q01TA', 'ST129Q02TA', 'ST129Q03TA', 'ST129Q04TA', 'ST129Q05TA', 'ST129Q06TA', 'ST129Q07TA', 'ST129Q08TA', 'ST131Q01NA', 'ST131Q03NA', 'ST131Q04NA', 'ST131Q06NA', 'ST131Q08NA', 'ST131Q11NA', 'ST146Q01TA', 'ST146Q02TA', 'ST146Q03TA', 'ST146Q04TA', 'ST146Q05TA', 'ST146Q06NA', 'ST146Q07NA', 'ST146Q08NA', 'ST146Q09NA', 'ST076Q01NA', 'ST076Q02NA', 'ST076Q03NA', 'ST076Q04NA', 'ST076Q05NA', 'ST076Q06NA', 'ST076Q07NA', 'ST076Q08NA', 'ST076Q09NA', 'ST076Q10NA', 'ST076Q11NA', 'ST078Q01NA', 'ST078Q02NA', 'ST078Q03NA', 'ST078Q04NA', 'ST078Q05NA', 'ST078Q06NA', 'ST078Q07NA', 'ST078Q08NA', 'ST078Q09NA', 'ST078Q10NA', 'ST078Q11NA', 'ST065Class', 'IC001Q01TA', 'IC001Q02TA', 'IC001Q03TA', 'IC001Q04TA', 'IC001Q05TA', 'IC001Q06TA', 'IC001Q07TA', 'IC001Q08TA', 'IC001Q09TA', 'IC001Q10TA', 'IC001Q11TA', 'IC009Q01TA', 'IC009Q02TA', 'IC009Q03TA', 'IC009Q05NA', 'IC009Q06NA', 'IC009Q07NA', 'IC009Q08TA', 'IC009Q09TA', 'IC009Q10NA', 'IC009Q11NA', 'IC002Q01NA', 'IC003Q01TA', 'IC004Q01TA', 'IC005Q01TA', 'IC006Q01TA', 'IC007Q01TA', 'IC008Q01TA', 'IC008Q02TA', 'IC008Q03TA', 'IC008Q04TA', 'IC008Q05TA', 'IC008Q07NA', 'IC008Q08TA', 'IC008Q09TA', 'IC008Q10TA', 'IC008Q11TA', 'IC008Q12TA', 'IC008Q13NA', 'IC010Q01TA', 'IC010Q02NA', 'IC010Q03TA', 'IC010Q04TA', 'IC010Q05NA', 'IC010Q06NA', 'IC010Q07TA', 'IC010Q08TA', 'IC010Q09NA', 'IC010Q10NA', 'IC010Q11NA', 'IC010Q12NA', 'IC011Q01TA', 'IC011Q02TA', 'IC011Q03TA', 'IC011Q04TA', 'IC011Q05TA', 'IC011Q06TA', 'IC011Q07TA', 'IC011Q08TA', 'IC011Q09TA', 'IC013Q01NA', 'IC013Q04NA', 'IC013Q05NA', 'IC013Q11NA', 'IC013Q12NA', 'IC013Q13NA', 'IC014Q03NA', 'IC014Q04NA', 'IC014Q06NA', 'IC014Q08NA', 'IC014Q09NA', 'IC015Q02NA', 'IC015Q03NA', 'IC015Q05NA', 'IC015Q07NA', 'IC015Q09NA', 'IC016Q01NA', 'IC016Q02NA', 'IC016Q04NA', 'IC016Q05NA', 'IC016Q07NA', 'EC001Q01NA', 'EC001Q02NA', 'EC001Q03NA', 'EC001Q04NA', 'EC001Q05NA', 'EC001Q06NA', 'EC001Q07NA', 'EC001Q08NA', 'EC001Q09NA', 'EC001Q10NA', 'EC003Q01NA', 'EC003Q02NA', 'EC003Q03NA', 'EC003Q04NA', 'EC003Q05NA', 'EC003Q06NA', 'EC004Q01NA', 'EC004Q02NA', 'EC005Q01NA', 'EC005Q02NA', 'EC005Q03NA', 'EC005Q04NA', 'EC005Q05NA', 'EC005Q06NA', 'EC005Q07NA', 'EC005Q08NA', 'EC007Q01NA', 'EC007Q02NA', 'EC008Q01NA', 'EC008Q02NA', 'EC008Q03NA', 'EC008Q04NA', 'EC009Q03NA', 'EC009Q07NA', 'EC009Q10NA', 'EC009Q12NA', 'EC009Q13NA', 'EC009Q14NA', 'EC010Q04NA', 'EC010Q06NA', 'EC010Q07NA', 'EC010Q08NA', 'EC010Q09NA', 'EC010Q10NA', 'EC010Q11NA', 'EC010Q12NA', 'EC011Q01NA', 'EC011Q02NA', 'EC011Q03NA', 'EC011Q04NA', 'EC011Q05NA', 'EC012Q01NA', 'EC012Q02NA', 'EC012Q03NA', 'EC012Q04NA', 'EC012Q05NA', 'EC012Q06NA', 'EC012Q07NA', 'EC012Q08NA', 'EC012Q09NA', 'EC012Q10NA', 'EC012Q11NA', 'EC012Q12NA', 'EC013Q01NA', 'EC013Q02NA', 'EC013Q03NA', 'EC013Q04NA', 'EC013Q05NA', 'EC013Q06NA', 'EC013Q07NA', 'EC013Q08NA', 'EC013Q09NA', 'EC013Q10NA', 'EC013Q11NA', 'EC013Q12NA', 'EC013Q13NA', 'EC014Q01NA', 'EC014Q02NA', 'EC015Q01NA', 'EC015Q02NA', 'EC015Q03NA', 'EC015Q04NA', 'EC015Q05NA', 'EC015Q06NA', 'EC015Q07NA', 'EC015Q08NA', 'EC017Q01NA', 'EC017Q02NA', 'EC018Q01NA', 'EC018Q02NA', 'EC018Q03NA', 'EC018Q04NA', 'EC019Q03NA', 'EC019Q07NA', 'EC019Q10NA', 'EC019Q12NA', 'EC019Q13NA', 'EC019Q14NA', 'EC020Q04NA', 'EC020Q06NA', 'EC020Q07NA', 'EC020Q08NA', 'EC020Q09NA', 'EC020Q10NA', 'EC020Q11NA', 'EC020Q12NA', 'EC021Q01NA', 'EC021Q02NA', 'EC021Q03NA', 'EC021Q04NA', 'EC021Q05NA', 'EC022Q01NA', 'EC022Q02NA', 'EC022Q03NA', 'EC022Q04NA', 'EC022Q05NA', 'EC022Q06NA', 'EC022Q07NA', 'EC022Q08NA', 'EC022Q09NA', 'EC022Q10NA', 'EC022Q11NA', 'EC022Q12NA', 'EC023Q01NA', 'EC023Q02NA', 'EC023Q03NA', 'EC023Q04NA', 'EC023Q05NA', 'EC023Q06NA', 'EC023Q07NA', 'EC023Q08NA', 'EC023Q09NA', 'EC023Q10NA', 'EC023Q11NA', 'EC023Q12NA', 'EC023Q13NA', 'EC024Q01NA', 'EC024Q02NA', 'EC024Q03NA', 'EC024Q04NA', 'EC024Q05NA', 'EC024Q06NA', 'EC024Q07NA', 'EC024Q08NA', 'EC026Q01NA', 'EC026Q02NA', 'EC027Q01NA', 'EC027Q02NA', 'EC027Q03NA', 'EC027Q04NA', 'EC028Q01NA', 'EC028Q02NA', 'EC028Q03NA', 'EC029Q01NA', 'EC030Q01NA', 'EC030Q02NA', 'EC030Q03NA', 'EC030Q04NA', 'EC030Q05NA', 'EC030Q06NA', 'EC030Q07NA', 'EC031Q01TA', 'EC032Q01TA', 'EC033Q01NA', 'PA001Q01TA', 'PA001Q02TA', 'PA001Q03TA', 'PA002Q01TA', 'PA002Q02TA', 'PA002Q03TA', 'PA002Q04TA', 'PA002Q05TA', 'PA002Q06NA', 'PA002Q07NA', 'PA002Q08NA', 'PA002Q09NA', 'PA002Q10NA', 'PA003Q01TA', 'PA003Q02TA', 'PA003Q03TA', 'PA003Q04NA', 'PA003Q05NA', 'PA003Q06NA', 'PA003Q07NA', 'PA003Q08NA', 'PA004Q01NA', 'PA004Q02NA', 'PA004Q03NA', 'PA004Q04NA', 'PA005Q01TA', 'PA006Q01TA', 'PA006Q02TA', 'PA006Q03TA', 'PA006Q04TA', 'PA006Q05TA', 'PA006Q06TA', 'PA006Q07TA', 'PA006Q08TA', 'PA006Q09TA', 'PA006Q10TA', 'PA006Q11TA', 'PA007Q01TA', 'PA007Q02TA', 'PA007Q03TA', 'PA007Q04TA', 'PA007Q05TA', 'PA007Q06TA', 'PA007Q07TA', 'PA007Q09NA', 'PA007Q11NA', 'PA007Q12NA', 'PA007Q13NA', 'PA007Q14NA', 'PA007Q15NA', 'PA008Q01TA', 'PA008Q02TA', 'PA008Q03TA', 'PA008Q04TA', 'PA008Q05TA', 'PA008Q06NA', 'PA008Q07NA', 'PA008Q08NA', 'PA008Q09NA', 'PA008Q10NA', 'PA009Q01NA', 'PA009Q02NA', 'PA009Q03NA', 'PA009Q04NA', 'PA009Q05NA', 'PA009Q06NA', 'PA009Q08NA', 'PA009Q09NA', 'PA009Q10NA', 'PA009Q11NA', 'PA011Q01NA', 'PA011Q02NA', 'PA011Q03NA', 'PA014Q01NA', 'PA018Q01NA', 'PA018Q02NA', 'PA018Q03NA', 'PA019Q01NA', 'PA019Q02NA', 'PA019Q03NA', 'PA019Q04NA', 'PA019Q05NA', 'PA019Q06NA', 'PA019Q07NA', 'PA019Q08NA', 'PA020Q01NA', 'PA020Q02NA', 'PA020Q03NA', 'PA020Q04NA', 'PA021Q01NA', 'PA021Q02NA', 'PA021Q03NA', 'PA021Q04NA', 'PA022Q01NA', 'PA023Q01NA', 'PA023Q02NA', 'PA023Q03NA', 'PA023Q04NA', 'PA023Q05NA', 'PA023Q06NA', 'PA023Q07NA', 'PA023Q08NA', 'PA026Q01NA', 'PA027Q01NA', 'PA027Q02NA', 'PA027Q03NA', 'PA027Q04NA', 'PA027Q05NA', 'PA027Q06NA', 'PA027Q07NA', 'PA027Q08NA', 'PA028Q01NA', 'PA029Q01NA', 'PA030Q01NA', 'PA032Q01TA', 'PA032Q02TA', 'PA032Q03TA', 'PA032Q04TA', 'PA032Q05TA', 'PA033Q02TA', 'PA033Q06TA', 'PA033Q07TA', 'PA033Q08TA', 'PA033Q09TA', 'PA035Q01TA', 'PA035Q03TA', 'PA035Q04TA', 'PA035Q05TA', 'PA035Q06TA', 'PA035Q07NA', 'PA035Q08NA', 'PA036Q01TA', 'PA036Q03TA', 'PA036Q04TA', 'PA036Q05TA', 'PA036Q06TA', 'PA036Q07NA', 'PA036Q08NA', 'PA039Q01TA', 'PA039Q02TA', 'PA039Q03TA', 'PA039Q04TA', 'PA039Q05TA', 'PA039Q06TA', 'PA041Q01TA', 'PA042Q01TA', 'AGE', 'PROGN', 'ISCEDL', 'ISCEDD', 'ISCEDO', 'DISCLISCI', 'TEACHSUP', 'IBTEACH', 'TDTEACH', 'ENVAWARE', 'ENVOPT', 'JOYSCIE', 'INTBRSCI', 'INSTSCIE', 'SCIEEFF', 'EPIST', 'SCIEACT', 'BSMJ', 'GRADE', 'IMMIG', 'MISCED', 'FISCED', 'HISCED', 'HOMESCH', 'ENTUSE', 'BMMJ1', 'BFMJ2', 'hisei', 'REPEAT', 'DURECEC', 'OUTHOURS', 'MMINS', 'LMINS', 'SMINS', 'TMINS', 'BELONG', 'ANXTEST', 'MOTIVAT', 'COOPERATE', 'CPSVALUE', 'EMOSUPS', 'PERFEED', 'ADINST', 'SCCHANGE', 'CHANGE', 'SADDINST', 'HADDINST', 'ADDSCIIN', 'COMSCSUP', 'COMSCSTRLE', 'COMSCSTRCO', 'COMSCTSREL', 'COMMASUP', 'COMMASTRLE', 'COMMASTRCO', 'COMMATSREL', 'USESCH', 'INTICT', 'COMPICT', 'AUTICT', 'SOIAICT', 'ICTHOME', 'ICTSCH', 'PRESUPP', 'CURSUPP', 'EMOSUPP', 'PQSCHOOL', 'PASCHPOL', 'PQGENSCI', 'PQENPERC', 'PQENVOPT', 'unfairteacher', 'PARED', 'COBN_F', 'COBN_M', 'COBN_S', 'LANGN', 'OCOD1', 'OCOD2', 'OCOD3', 'CULTPOSS', 'HEDRES', 'HOMEPOS', 'ICTRES', 'WEALTH', 'ESCS', 'W_FSTUWT', 'W_FSTURWT1', 'W_FSTURWT2', 'W_FSTURWT3', 'W_FSTURWT4', 'W_FSTURWT5', 'W_FSTURWT6', 'W_FSTURWT7', 'W_FSTURWT8', 'W_FSTURWT9', 'W_FSTURWT10', 'W_FSTURWT11', 'W_FSTURWT12', 'W_FSTURWT13', 'W_FSTURWT14', 'W_FSTURWT15', 'W_FSTURWT16', 'W_FSTURWT17', 'W_FSTURWT18', 'W_FSTURWT19', 'W_FSTURWT20', 'W_FSTURWT21', 'W_FSTURWT22', 'W_FSTURWT23', 'W_FSTURWT24', 'W_FSTURWT25', 'W_FSTURWT26', 'W_FSTURWT27', 'W_FSTURWT28', 'W_FSTURWT29', 'W_FSTURWT30', 'W_FSTURWT31', 'W_FSTURWT32', 'W_FSTURWT33', 'W_FSTURWT34', 'W_FSTURWT35', 'W_FSTURWT36', 'W_FSTURWT37', 'W_FSTURWT38', 'W_FSTURWT39', 'W_FSTURWT40', 'W_FSTURWT41', 'W_FSTURWT42', 'W_FSTURWT43', 'W_FSTURWT44', 'W_FSTURWT45', 'W_FSTURWT46', 'W_FSTURWT47', 'W_FSTURWT48', 'W_FSTURWT49', 'W_FSTURWT50', 'W_FSTURWT51', 'W_FSTURWT52', 'W_FSTURWT53', 'W_FSTURWT54', 'W_FSTURWT55', 'W_FSTURWT56', 'W_FSTURWT57', 'W_FSTURWT58', 'W_FSTURWT59', 'W_FSTURWT60', 'W_FSTURWT61', 'W_FSTURWT62', 'W_FSTURWT63', 'W_FSTURWT64', 'W_FSTURWT65', 'W_FSTURWT66', 'W_FSTURWT67', 'W_FSTURWT68', 'W_FSTURWT69', 'W_FSTURWT70', 'W_FSTURWT71', 'W_FSTURWT72', 'W_FSTURWT73', 'W_FSTURWT74', 'W_FSTURWT75', 'W_FSTURWT76', 'W_FSTURWT77', 'W_FSTURWT78', 'W_FSTURWT79', 'W_FSTURWT80', 'UNIT', 'WVARSTRR', 'PV1MATH', 'PV2MATH', 'PV3MATH', 'PV4MATH', 'PV5MATH', 'PV6MATH', 'PV7MATH', 'PV8MATH', 'PV9MATH', 'PV10MATH', 'PV1READ', 'PV2READ', 'PV3READ', 'PV4READ', 'PV5READ', 'PV6READ', 'PV7READ', 'PV8READ', 'PV9READ', 'PV10READ', 'PV1SCIE', 'PV2SCIE', 'PV3SCIE', 'PV4SCIE', 'PV5SCIE', 'PV6SCIE', 'PV7SCIE', 'PV8SCIE', 'PV9SCIE', 'PV10SCIE', 'PV1SCEP', 'PV2SCEP', 'PV3SCEP', 'PV4SCEP', 'PV5SCEP', 'PV6SCEP', 'PV7SCEP', 'PV8SCEP', 'PV9SCEP', 'PV10SCEP', 'PV1SCED', 'PV2SCED', 'PV3SCED', 'PV4SCED', 'PV5SCED', 'PV6SCED', 'PV7SCED', 'PV8SCED', 'PV9SCED', 'PV10SCED', 'PV1SCID', 'PV2SCID', 'PV3SCID', 'PV4SCID', 'PV5SCID', 'PV6SCID', 'PV7SCID', 'PV8SCID', 'PV9SCID', 'PV10SCID', 'PV1SKCO', 'PV2SKCO', 'PV3SKCO', 'PV4SKCO', 'PV5SKCO', 'PV6SKCO', 'PV7SKCO', 'PV8SKCO', 'PV9SKCO', 'PV10SKCO', 'PV1SKPE', 'PV2SKPE', 'PV3SKPE', 'PV4SKPE', 'PV5SKPE', 'PV6SKPE', 'PV7SKPE', 'PV8SKPE', 'PV9SKPE', 'PV10SKPE', 'PV1SSPH', 'PV2SSPH', 'PV3SSPH', 'PV4SSPH', 'PV5SSPH', 'PV6SSPH', 'PV7SSPH', 'PV8SSPH', 'PV9SSPH', 'PV10SSPH', 'PV1SSLI', 'PV2SSLI', 'PV3SSLI', 'PV4SSLI', 'PV5SSLI', 'PV6SSLI', 'PV7SSLI', 'PV8SSLI', 'PV9SSLI', 'PV10SSLI', 'PV1SSES', 'PV2SSES', 'PV3SSES', 'PV4SSES', 'PV5SSES', 'PV6SSES', 'PV7SSES', 'PV8SSES', 'PV9SSES', 'PV10SSES', 'SENWT', 'VER_DAT']

In [6]:
keywords = ["job", "career", "future", "science", "important", "worthwhile", "useful"]
for name, label in zip(meta.column_names, meta.column_labels):
    if any(kw.lower() in str(label).lower() for kw in keywords):
        print(name, ":", label)

Option_ECQ : Educational Career Questionnaire Option
CBASCI : Science Cluster Combination Random Number (S)
ST059Q03TA : Number of <class periods> required per week in <science>
ST071Q01NA : This school year, approximately how many hours per week do you spend learning in addition? <School Science>
ST063Q01NA : Which <school science> course did you attend? Physics: This year
ST063Q01NB : Which <school science> course did you attend? Physics: Last year
ST063Q02NA : Which <school science> course did you attend? Chemistry: This year
ST063Q02NB : Which <school science> course did you attend? Chemistry: Last year
ST063Q03NA : Which <school science> course did you attend? Biology: This year
ST063Q03NB : Which <school science> course did you attend? Biology: Last year
ST063Q04NA : Which <school science> course did you attend? <Earth and space>: This year
ST063Q04NB : Which <school science> course did you attend? <Earth and space>: Last year
ST063Q05NA : Which <school science> course did you attend? Applied sciences and technology: This year
ST063Q05NB : Which <school science> course did you attend? Applied sciences and technology: Last year
ST063Q06NA : Which <school science> course did you attend? <General, integrated, or comprehen science> course: This year
ST063Q06NB : Which <school science> course did you attend? <General, integrated, or comprehen science> course: Last year
ST064Q01NA : <school science> courses? I can choose the <school science> course(s) I study.
ST064Q02NA : <school science> courses? I can choose the level of difficulty.
ST064Q03NA : <school science> courses? I can choose the number of <school science> courses or <class periods>.
ST097Q01TA : How often does this happen in your <school science> lessons? Students don't listen to what the teacher says.
ST097Q02TA : How often does this happen in your <school science> lessons? There is noise and disorder.
ST097Q03TA : How often does this happen in your <school science> lessons? The teacher waits long for students to quiet down.
ST097Q04TA : How often does this happen in your <school science> lessons? Students cannot work well.
ST097Q05TA : How often does this happen in your <school science> lessons? Students don't start working for a long time after.
ST098Q01TA : When learning <school science>? Students are given opportunities to explain their ideas.
ST098Q02TA : When learning <school science>? Students spend time in the laboratory doing practical experiments.
ST098Q03NA : When learning <school science>? Students are required to argue about science questions.
ST098Q05TA : When learning <school science>? Students are asked to draw conclusions from an experiment they have conducted.
ST098Q06TA : When learning <school science>? The teacher explains <school science> idea can be applied
ST098Q07TA : When learning <school science>? Students are allowed to design their own experiments.
ST098Q08NA : When learning <school science>? There is a class debate about investigations.
ST098Q09TA : When learning <school science>? The teacher clearly explains relevance  <broad science> concepts to our lives.
ST098Q10NA : When learning <school science>? Students are asked to do an investigation to test ideas.
ST100Q01TA : How often does this happen in your <school science> lessons? The teacher shows  interest every students learning.
ST100Q02TA : How often does this happen in your <school science> lessons? The teacher gives extra help.
ST100Q03TA : How often does this happen in your <school science> lessons? The teacher helps students with their learning.
ST100Q04TA : How often does this happen in your <school science>? The teacher continues teaching\students understand.
ST100Q05TA : How often does this happen in your <school science>? Teacher gives an opportunity to express opinions.
ST103Q01NA : How often does this happen in <school science>? The teacher explains scientific ideas.
ST103Q03NA : How often does this happen in <school science>? A whole class discussion takes place with the teacher.
ST103Q08NA : How often does this happen in <school science>? The teacher discusses our questions.
ST103Q11NA : How often does this happen in <school science>? The teacher demonstrates an idea.
ST104Q01NA : How often does this happen in <school science>? The teacher tells me how I am performing in this course.
ST104Q02NA : How often does this happen in <school science>? The teacher gives me feedback on my strengths <school science> subjec
ST104Q03NA : How often does this happen in <school science>? The teacher tells me in which areas I can still improve.
ST104Q04NA : How often does this happen in <school science>? The teacher tells me how I can improve my performance.
ST104Q05NA : How often does this happen in <school science>? The teacher advises me on how to reach my learning goals.
ST107Q01NA : How often does this happen in <school science>? The teacher adapts the lesson to my class needs and knowledge.
ST107Q02NA : How often does this happen in <school science>? The teacher provides individual help when a student has difficulties
ST107Q03NA : How often does this happen in <school science>? The teacher changes the structure of the lesson on a topic
ST094Q01NA : Disagree or agree with the statements? I have fun when I am learning <broad science>
ST094Q02NA : Disagree or agree with the statements? I like reading about <broad science> topics.
ST094Q03NA : Disagree or agree with the statements? I am happy working on <broad science> topics.
ST094Q04NA : Disagree or agree with the statements? I enjoy acquiring new knowledge in <broad science>.
ST094Q05NA : Disagree or agree with the statements? I am interested in learning about <broad science>.
ST095Q13NA : To what extent are you interested in: <broad science> topics? The Universe and its history
ST095Q15NA : To what extent are you interested in: <broad science> topics? How science can help us prevent disease
ST113Q01TA : Making an effort in my <school science> subject(s) is worth it because this will help me in the work I want to do lat
ST113Q02TA : What I learn in my <school science> subject(s) is important for me because I need this for what I want to do later on
ST113Q03TA : Studying my <school science> subject(s) is worthwhile for me because what I learn will improve my career prospects.
ST113Q04TA : Many things I learn in my <school science> subject(s) will help me to get a job.
ST129Q01TA : Recognise the science question that underlies a newspaper report on a health issue.
ST129Q04TA : Identify the science question associated with the disposal of garbage.
ST131Q03NA : How much do you disagree or agree with the statements below? Ideas in <broad science> sometimes change.
ST131Q08NA : Sometimes <broad science> scientists change their minds about what is true
ST131Q11NA : The ideas in <broad science> science books sometimes change.
ST146Q01TA : How often do you do these things? Watch TV programmes about <broad science>
ST146Q02TA : How often do you do these things? Borrow or buy books on <broad science> topics
ST146Q03TA : How often do you do these things? Visit web sites about <broad science> topics
ST146Q04TA : How often do you do these things? Read <broad science> magazines or science articles in newspapers
ST146Q05TA : How often do you do these things? Attend a <science club>
ST065Class : Student coded science class (from ST065Q01NA)
IC010Q12NA : Frequency of use outside of school: Downloading science learning apps on a mobile device.
IC013Q05NA : It is very useful to have Social Networks on the Internet.
EC001Q01NA : Approx how many hrs\week attend add. instruct in the follow. domains? <School science> or <broad science>
EC001Q05NA : Approx how many hrs\week attend add. instruct in the follow. domains? Social sciences
EC003Q01NA : Which <school science> subjects are covered? Physics
EC003Q02NA : Which <school science> subjects are covered? Chemistry
EC003Q03NA : Which <school science> subjects are covered? Biology
EC003Q04NA : Which <school science> subjects are covered? <Earth and space>
EC003Q05NA : Which <school science> subjects are covered? Applied science and technology (e.g. <country-specific example>)
EC003Q06NA : Which <school science> subjects are covered? <General or integrated science> (e.g. <country-specific example>)
EC004Q01NA : Add science inst. cover? Content covered in regular school courses
EC004Q02NA : Add science inst. cover? New or additional content not covered in regular school courses
EC005Q08NA : Sci. instruct. participate? Other additional science instruction
EC007Q01NA : Where do you attend this additional science instruction? In my regular school building
EC007Q02NA : Where do you attend this additional science instruction? At some other place, i.e., not in my reg school building
EC008Q01NA : The teacher is one of my regular teachers in this years school courses. (science)
EC008Q02NA : The teacher regularly teaches students my age in school but is not my teacher in any of my regular courses. (science)
EC008Q03NA : The teacher mainly works for a business or organisation specialised in additional instruction. (science)
EC008Q04NA : The teacher is not specialised teaching personnel (e.g. a student). (science)
EC009Q03NA : Compare your <school science> lessons at school\your add sci inst. My teacher does a lot to help
EC009Q07NA : Compare your <school science> lessons at school\your add sci inst. My teacher is pleased when I
EC009Q10NA : Compare your <school science> lessons at school\your add sci inst. My teacher gives hints
EC009Q12NA : Compare your <school science> lessons at school\your add sci inst. My teacher helps me\find ways
EC009Q13NA : Compare your <school science> lessons at school\your add sci inst. Once we identify why
EC009Q14NA : Compare your <school science> lessons at school\your add sci inst. My teacher adapts the content
EC010Q04NA : Compare <school science> lessons in school\add sci instruct. It takes long time until I have gathered all the materia
EC010Q06NA : Compare <school science> lessons in school\add sci instruct. I talk about things that don't have anything to do with
EC010Q07NA : Compare <school science> lessons in school\add sci instruct. At the end of a lesson, my teacher summarises learning
EC010Q08NA : Compare <school science> lessons in school\add sci instruct. My teacher points out the most important aspects\topic.
EC010Q09NA : Compare <school science> lessons in school\add sci instruct. I am often bored.
EC010Q10NA : Compare <school science> lessons in school\add sci instruct. It takes very long until I am ready to get started.
EC010Q11NA : Compare <school science> lessons in school\add sci instruct. I should learn in a cert actvty.
EC010Q12NA : Compare <school science> lessons in school\add sci instruct. My teacher points out the broader context of a learning
EC011Q01NA : Compare <school science> lessons in school\add sci instruct. I get along well with my teachers.
EC011Q02NA : Compare <school science> lessons in school\add sci instruct. My teachers are interested in my well-being.
EC011Q03NA : Compare <school science> lessons in school\add sci instruct. My teachers really listen to what I have to say.
EC011Q04NA : Compare <school science> lessons in school\add sci instruct. If I need extra help, I will receive it from teachers.
EC011Q05NA : Compare <school science> lessons in school\add sci instruct. My teachers treat me fairly.
EC012Q01NA : Why do you attend additional science instruction in this school year? I want to learn more.
EC012Q02NA : Why do you attend additional science instruction in this school year? I want to prepare for exams.
EC012Q03NA : Why do you attend additional science instruction in this school year? I was attracted by the tutoring advertisement.
EC012Q04NA : Why do you attend additional science instruction in this school year? My parents wanted me to attend.
EC012Q05NA : Why do you attend additional science instruction in this school year? Many of my friends are doing it.
EC012Q06NA : Why do you attend additional science instruction in this school year? My teachers recommend it.
EC012Q07NA : Why do you attend additional science instruction in this school year? I want to improve my grades.
EC012Q08NA : Why do you attend additional science instruction in this school year? I need to improve my grades.
EC012Q09NA : Why do you attend additional science instruction in this school year? It is gratifying to study.
EC012Q10NA : Why do you attend additional science instruction in this school year? It looks good on a résumé.
EC012Q11NA : Why do you attend additional science instruction in this school year? It is necessary for a job.
EC012Q12NA : Why do you attend additional science instruction in this school year? Other reason.
EC013Q01NA : Why don't you attend additional science in this school year? I don't need any additional science instruction.
EC013Q02NA : Why don't you attend additional science in this school year? None of the available offerings suit my needs.
EC013Q03NA : Why don't you attend additional science in this school year? Not many of my friends are doing it.
EC013Q04NA : Why don't you attend additional science in this school year? I don't have time.
EC013Q05NA : Why don't you attend additional science in this school year? I don't have the money.
EC013Q06NA : Why don't you attend additional science in this school year? My school teachers are knowledgeable enough.
EC013Q07NA : Why don't you attend additional science in this school year? My parents don't want me to do it.
EC013Q08NA : Why don't you attend additional science in this school year? It doesnt seem worth the money.
EC013Q09NA : Why don't you attend additional science in this school year? My teachers say it is not useful.
EC013Q10NA : Why don't you attend additional science in this school year? I have never considered add. science instruction.
EC013Q11NA : Why don't you attend additional science in this school year? Add. science instruction not avail. where I live.
EC013Q12NA : Why don't you attend additional science in this school year? My family helps me instead.
EC013Q13NA : Why don't you attend additional science in this school year? My peers and friends help me instead.
EC020Q08NA : Where do math situations occur? My teacher points out the most important aspects of a topic.
EC022Q11NA : Why do you attend additional mathematics in this school year: It is necessary for a job.
EC023Q09NA : Why don't you attend additional mathematics in this school year: My teachers say it is not useful.
PA002Q01TA : Watched TV programmes about science
PA002Q03TA : Watched, read or listened to science fiction
PA002Q04TA : Visited web sites about science topics
PA002Q05TA : Attended a science club
PA002Q09NA : Experimented with a science kit, electronics kit, or chemistry set, used a microscope or telescope
PA002Q10NA : Played computer games with a science content
PA003Q04NA : Help my child with his\her science homework.
PA003Q05NA : Ask how my child is performing in science class.
PA003Q06NA : Obtain science-related materials (e.g., applications, software, study guides etc.) for my child.
PA003Q07NA : Discuss with my child how science is used in everyday life.
PA003Q08NA : Discuss <science related career> options with my child.
PA007Q06TA : My childs school provides regular and useful information on my childs progress.
PA007Q07TA : My childs school does a good job in educating students.
PA022Q01NA : What was the most important reason why your child attended a <supervision and care arrangement>?
PA026Q01NA : What was the most important reason why your child attended an <early childhood educational development arrangement>?
PA030Q01NA : What was the most important reason why your child attended a <pre-primary education arrangement>?
PA032Q01TA : Does anybody in your family (including you) work in a <science-related career>?
PA032Q02TA : Does your child show an interest in working in a <science-related career>?
PA032Q03TA : Do you expect your child will go into a < science-related career>?
PA032Q04TA : Has your child shown interest in studying science after completing <secondary school>?
PA032Q05TA : Do you expect your child will study science after completing <secondary school>?
PA033Q02TA : Parent views toward science: <Broad science> is important to help us to understand the natural world.
PA033Q06TA : How much do you agree: <Broad science> is valuable to society.
PA033Q07TA : How much do you agree: <Broad science> is very relevant to me.
PA033Q08TA : How much do you agree: I find that <broad science> helps me to understand the things around me.
PA033Q09TA : How much do you agree: Advances in <broad science> usually bring social benefits.
DISCLISCI : Disciplinary climate in science classes (WLE)
TEACHSUP : Teacher support in a science classes of students choice (WLE)
IBTEACH : Inquiry-based science teaching an learning practices (WLE)
TDTEACH : Teacher-directed science instruction (WLE)
JOYSCIE : Enjoyment of science (WLE)
INTBRSCI : Interest in broad science topics (WLE)
SCIEEFF : Science self-efficacy (WLE)
SCIEACT : Index science activities (WLE)
SMINS : Learning time (minutes per week) - <science>
ADDSCIIN : Number of science disciplines and subjects  with additional instruction (Sum)
COMSCSUP : Comparison science school lessons and additional instruction support (Mean)
COMSCSTRLE : Comparison science school lessons and additional instruction structuredness lessons (Mean)
COMSCSTRCO : Comparison science school lessons and additional instruction structuredness content (Mean)
COMSCTSREL : Comparison science school lessons and additional instruction teacher-student relation
PRESUPP : Child’s past science activities (WLE)
PQGENSCI : Parents’ view on science (WLE)
PQENVOPT : Parents’ view on future environmental topics (WLE)
PV1SCIE : Plausible Value 1 in Science
PV2SCIE : Plausible Value 2 in Science
PV3SCIE : Plausible Value 3 in Science
PV4SCIE : Plausible Value 4 in Science
PV5SCIE : Plausible Value 5 in Science
PV6SCIE : Plausible Value 6 in Science
PV7SCIE : Plausible Value 7 in Science
PV8SCIE : Plausible Value 8 in Science
PV9SCIE : Plausible Value 9 in Science
PV10SCIE : Plausible Value 10 in Science
PV1SCEP : Plausible Value 1 in Competency Subscale of Science - Explain Phenomena Scientifically
PV2SCEP : Plausible Value 2 in Competency Subscale of Science - Explain Phenomena Scientifically
PV3SCEP : Plausible Value 3 in Competency Subscale of Science - Explain Phenomena Scientifically
PV4SCEP : Plausible Value 4 in Competency Subscale of Science - Explain Phenomena Scientifically
PV5SCEP : Plausible Value 5 in Competency Subscale of Science - Explain Phenomena Scientifically
PV6SCEP : Plausible Value 6 in Competency Subscale of Science - Explain Phenomena Scientifically
PV7SCEP : Plausible Value 7 in Competency Subscale of Science - Explain Phenomena Scientifically
PV8SCEP : Plausible Value 8 in Competency Subscale of Science - Explain Phenomena Scientifically
PV9SCEP : Plausible Value 9 in Competency Subscale of Science - Explain Phenomena Scientifically
PV10SCEP : Plausible Value 10 in Competency Subscale of Science - Explain Phenomena Scientifically
PV1SCED : Plausible Value 1 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV2SCED : Plausible Value 2 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV3SCED : Plausible Value 3 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV4SCED : Plausible Value 4 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV5SCED : Plausible Value 5 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV6SCED : Plausible Value 6 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV7SCED : Plausible Value 7 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry
PV8SCED : Plausible Value 8 in Competency Subscale of Science - Evaluate and Design Scientific Enquiry

In [7]:
turkey_df = df[df['CNT'] == 'TUR']

In [8]:
turkey_df

,CNTRYID,CNT,CNTSCHID,CNTSTUID,CYC,NatCen,Region,STRATUM,SUBNATIO,OECD,...,PV3SSES,PV4SSES,PV5SSES,PV6SSES,PV7SSES,PV8SSES,PV9SSES,PV10SSES,SENWT,VER_DAT
433419,792.0,TUR,79200001.0,79200939.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,415.111,397.101,377.839,466.979,433.130,431.024,469.658,415.568,1.04545,15NOV16:12:26:00
433420,792.0,TUR,79200001.0,79206774.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,290.778,280.965,352.460,356.424,291.665,352.781,363.644,346.106,1.04545,15NOV16:12:26:00
433421,792.0,TUR,79200001.0,79204670.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,388.810,339.885,375.632,357.794,432.564,316.906,430.629,367.299,1.04545,15NOV16:12:26:00
433422,792.0,TUR,79200001.0,79201647.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,359.652,284.302,296.940,258.184,333.335,363.671,357.667,360.436,1.04545,15NOV16:12:26:00
433423,792.0,TUR,79200001.0,79203718.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,398.480,433.419,397.766,376.304,346.781,370.015,404.469,414.817,1.04545,15NOV16:12:26:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439309,792.0,TUR,79200231.0,79202468.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,475.812,408.638,481.304,440.262,435.158,479.475,410.473,404.953,0.67779,15NOV16:12:26:00
439310,792.0,TUR,79200231.0,79203877.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,436.599,486.450,449.778,479.466,503.927,454.335,472.065,514.995,0.67779,15NOV16:12:26:00
439311,792.0,TUR,79200231.0,79202467.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,510.299,513.320,502.201,527.267,510.005,482.383,477.601,481.269,0.67779,15NOV16:12:26:00
439312,792.0,TUR,79200231.0,79204664.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,501.679,405.887,428.410,403.289,437.303,421.398,413.469,390.650,0.67779,15NOV16:12:26:00
439313,792.0,TUR,79200231.0,79203767.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,401.240,446.910,437.370,438.307,449.654,466.361,385.807,471.616,0.67779,15NOV16:12:26:00

In [9]:
turkey_df.columns

Index(['CNTRYID', 'CNT', 'CNTSCHID', 'CNTSTUID', 'CYC', 'NatCen', 'Region',
       'STRATUM', 'SUBNATIO', 'OECD',
       ...
       'PV3SSES', 'PV4SSES', 'PV5SSES', 'PV6SSES', 'PV7SSES', 'PV8SSES',
       'PV9SSES', 'PV10SSES', 'SENWT', 'VER_DAT'],
      dtype='object', length=921)

In [10]:
# search for relevant patterns
motivation_cols = [col for col in turkey_df.columns if col.startswith('ST113')]
selfeff_cols = [col for col in turkey_df.columns if col.startswith('ST129')]

In [11]:
# Check variable labels for relevant variables
for var in [*motivation_cols, *selfeff_cols]:
    print(var, ":", meta.column_labels[meta.column_names.index(var)])

ST113Q01TA : Making an effort in my <school science> subject(s) is worth it because this will help me in the work I want to do lat
ST113Q02TA : What I learn in my <school science> subject(s) is important for me because I need this for what I want to do later on
ST113Q03TA : Studying my <school science> subject(s) is worthwhile for me because what I learn will improve my career prospects.
ST113Q04TA : Many things I learn in my <school science> subject(s) will help me to get a job.
ST129Q01TA : Recognise the science question that underlies a newspaper report on a health issue.
ST129Q02TA : Explain why earthquakes occur more frequently in some areas than in others.
ST129Q03TA : Describe the role of antibiotics in the treatment of disease.
ST129Q04TA : Identify the science question associated with the disposal of garbage.
ST129Q05TA : Predict how changes to an environment will affect the survival of certain species.
ST129Q06TA : Interpret the scientific information provided on the labelling of food items.
ST129Q07TA : Discuss how new evidence can lead you to change your understanding about the possibility of life on Mars.
ST129Q08TA : Identify the better of two explanations for the formation of acid rain.

In [12]:
motivation_items = ["ST113Q01TA", "ST113Q02TA", "ST113Q03TA", "ST113Q04TA"]
selfeff_items    = ["ST129Q01TA", "ST129Q02TA", "ST129Q03TA", "ST129Q04TA",
                    "ST129Q05TA", "ST129Q06TA", "ST129Q07TA", "ST129Q08TA"]
all_items = motivation_items + selfeff_items

In [13]:
# replace every occurrence of the numeric codes 7, 8, or 9 in the entire DataFrame turkey_df with NaN
clean_df = turkey_df.replace({7: np.nan, 8: np.nan, 9: np.nan})
# drop all rows (students, cases, etc.) that have missing values (NaN) in any of the columns listed in all_items
clean_df = clean_df.dropna(subset=all_items)

In [14]:
print("Remaining after removing missing:", clean_df.shape)

Remaining after removing missing: (5118, 921)

In [15]:
# Calculate z-scores for all relevant columns
z_scores = np.abs(stats.zscore(clean_df[all_items]))
# Identify rows where any z-score exceeds 3 (common threshold for univariate outliers)
outliers_univ = (z_scores > 3).any(axis=1)
# Remove univariate outliers
clean_df = clean_df[~outliers_univ]
print("After removing univariate outliers:", clean_df.shape)

After removing univariate outliers: (5118, 921)

In [16]:
# Calculate Mahalanobis distance for multivariate outlier detection
data = clean_df[all_items]
# Compute the covariance matrix and its inverse
cov = np.cov(data, rowvar=False)
cov_inv = np.linalg.inv(cov)
# Compute the mean vector
mean_vec = data.mean(axis=0)

# Calculate Mahalanobis distance for each row
md = data.apply(lambda row: mahalanobis(row, mean_vec, cov_inv), axis=1)
# Determine the threshold for identifying outliers
threshold = stats.chi2.ppf(0.999, df=len(all_items))  # 99.9% cutoff

# Remove multivariate outliers
clean_df = clean_df[md < np.sqrt(threshold)]
print("After removing multivariate outliers:", clean_df.shape)

After removing multivariate outliers: (4895, 921)

In [22]:
# Convert the two lists to a dictionary
col_labels_dict = dict(zip(meta.column_names, meta.column_labels))

# Now this will work
labels = [col_labels_dict.get(i, i) for i in all_items]

# Build the normality summary table
skewness = clean_df[all_items].skew()
kurtosis = clean_df[all_items].kurtosis()

normal_check = pd.DataFrame({
    "Item": all_items,
    "Question": labels,
    "Skewness": skewness.values,
    "Kurtosis": kurtosis.values
}).round(3)

pd.set_option('display.max_colwidth', None)
print(normal_check)

          Item  \
0   ST113Q01TA
1   ST113Q02TA
2   ST113Q03TA
3   ST113Q04TA
4   ST129Q01TA
5   ST129Q02TA
6   ST129Q03TA
7   ST129Q04TA
8   ST129Q05TA
9   ST129Q06TA
10  ST129Q07TA
11  ST129Q08TA

                                                                                                                 Question  \
0   Making an effort in my <school science> subject(s) is worth it because this will help me in the work I want to do lat
1   What I learn in my <school science> subject(s) is important for me because I need this for what I want to do later on
2     Studying my <school science> subject(s) is worthwhile for me because what I learn will improve my career prospects.
3                                        Many things I learn in my <school science> subject(s) will help me to get a job.
4                                     Recognise the science question that underlies a newspaper report on a health issue.
5                                             Explain why earthquakes occur more frequently in some areas than in others.
6                                                           Describe the role of antibiotics in the treatment of disease.
7                                                  Identify the science question associated with the disposal of garbage.
8                                      Predict how changes to an environment will affect the survival of certain species.
9                                           Interpret the scientific information provided on the labelling of food items.
10              Discuss how new evidence can lead you to change your understanding about the possibility of life on Mars.
11                                                Identify the better of two explanations for the formation of acid rain.

    Skewness  Kurtosis
0      0.722     0.282
1      0.637     0.230
2      0.582    -0.140
3      0.513    -0.344
4      0.790     0.471
5      0.736     0.311
6      0.548    -0.311
7      0.629    -0.047
8      0.589    -0.139
9      0.538    -0.272
10     0.413    -0.653
11     0.594    -0.344

In [25]:
# Create a new DataFrame 'X' that includes all CFA items plus a constant column (for intercept)
# The constant is needed because VIF calculations assume a regression model with an intercept.
X = clean_df[all_items].assign(const=1)

# Initialize an empty DataFrame to store VIF results
vif_data = pd.DataFrame()

# Add a column listing the variable (item) names
vif_data["Variable"] = all_items

# Compute the Variance Inflation Factor (VIF) for each variable
# VIF measures how much a variable is linearly correlated with other variables.
# High VIF (>5 or >10) indicates multicollinearity — i.e., redundant variables.
vif_data["VIF"] = [
    variance_inflation_factor(X.values, i)
    for i in range(len(all_items))
]

# Print the table showing each variable and its corresponding VIF value
print(vif_data)

      Variable       VIF
0   ST113Q01TA  3.173424
1   ST113Q02TA  3.897791
2   ST113Q03TA  3.442276
3   ST113Q04TA  2.666394
4   ST129Q01TA  1.868487
5   ST129Q02TA  2.177876
6   ST129Q03TA  2.070911
7   ST129Q04TA  2.363803
8   ST129Q05TA  2.388710
9   ST129Q06TA  2.297267
10  ST129Q07TA  1.857166
11  ST129Q08TA  2.106317

In [28]:
clean_df.dropna(subset=all_items)

,CNTRYID,CNT,CNTSCHID,CNTSTUID,CYC,NatCen,Region,STRATUM,SUBNATIO,OECD,...,PV3SSES,PV4SSES,PV5SSES,PV6SSES,PV7SSES,PV8SSES,PV9SSES,PV10SSES,SENWT,VER_DAT
433419,792.0,TUR,79200001.0,79200939.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,415.111,397.101,377.839,466.979,433.130,431.024,469.658,415.568,1.04545,15NOV16:12:26:00
433420,792.0,TUR,79200001.0,79206774.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,290.778,280.965,352.460,356.424,291.665,352.781,363.644,346.106,1.04545,15NOV16:12:26:00
433421,792.0,TUR,79200001.0,79204670.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,388.810,339.885,375.632,357.794,432.564,316.906,430.629,367.299,1.04545,15NOV16:12:26:00
433422,792.0,TUR,79200001.0,79201647.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,359.652,284.302,296.940,258.184,333.335,363.671,357.667,360.436,1.04545,15NOV16:12:26:00
433423,792.0,TUR,79200001.0,79203718.0,06MS,079200,79200.0,TUR0235,7920000,1.0,...,398.480,433.419,397.766,376.304,346.781,370.015,404.469,414.817,1.04545,15NOV16:12:26:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439308,792.0,TUR,79200231.0,79203231.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,426.727,444.609,406.769,422.664,437.853,416.682,442.741,419.693,0.67779,15NOV16:12:26:00
439309,792.0,TUR,79200231.0,79202468.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,475.812,408.638,481.304,440.262,435.158,479.475,410.473,404.953,0.67779,15NOV16:12:26:00
439310,792.0,TUR,79200231.0,79203877.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,436.599,486.450,449.778,479.466,503.927,454.335,472.065,514.995,0.67779,15NOV16:12:26:00
439311,792.0,TUR,79200231.0,79202467.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,510.299,513.320,502.201,527.267,510.005,482.383,477.601,481.269,0.67779,15NOV16:12:26:00
439312,792.0,TUR,79200231.0,79204664.0,06MS,079200,79200.0,TUR0226,7920000,1.0,...,501.679,405.887,428.410,403.289,437.303,421.398,413.469,390.650,0.67779,15NOV16:12:26:00

### The reasons behind difference in the rows presented in the paper and in our processing above:

The discrepancy arises mainly because the paper used the restricted Turkish national PISA 2015 file, while we are using the OECD public-use file, which merges strata, retains replacements, and encodes missing data differently.

After filtering to Turkey (Form TA), converting 7/8/9 → NaN, dropping incomplete gender/region cases, and removing outliers, our sample becomes functionally equivalent.
Any remaining ~300-row gap is due to confidentiality-driven regional merging and polychoric-based exclusion in the original study—unfixable without the restricted file but negligible for inference.

In [29]:
keep_cols = [
    "CNTRYID", "CNT", "CNTSCHID", "CNTSTUID",
    "STRATUM", "LANGTEST_QQQ", "ST004D01T",
    "ST113Q01TA", "ST113Q02TA", "ST113Q03TA", "ST113Q04TA",
    "ST129Q01TA", "ST129Q02TA", "ST129Q03TA", "ST129Q04TA",
    "ST129Q05TA", "ST129Q06TA", "ST129Q07TA", "ST129Q08TA"
]

final_df = clean_df[keep_cols]
print(final_df.shape)

(4895, 19)

In [ ]:
import rpy2.robjects as ro
# Import the pandas2ri module for DataFrame conversion
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.

In [31]:
# Convert Pandas → R safely
with localconverter(ro.default_converter + pandas2ri.converter):
    ro.globalenv['pisa_data'] = ro.conversion.py2rpy(clean_df)

In [32]:
ro.r('R.version.string')

<rpy2.robjects.vectors.StrVector object at 0x00000235CB05AF90> [16]
R classes: ('character',)
['R version 4.5.2 (2025-10-31 ucrt)']

In [33]:
# Now run your R code
ro.r('''  # This sends the following multi-line R code block to R for execution via rpy2
library(lavaan)  
# Load the lavaan package (the main library for SEM/CFA in R)

model <- '
  MOT =~ ST113Q01TA + ST113Q02TA + ST113Q03TA + ST113Q04TA
  SCIEFF =~ ST129Q01TA + ST129Q02TA + ST129Q03TA + ST129Q04TA +
             ST129Q05TA + ST129Q06TA + ST129Q07TA + ST129Q08TA
'
# Define the CFA model using lavaan’s model syntax.
# Each line defines a latent variable (factor) and the items that "load" onto it.
#   - MOT     → latent factor for "Instrumental Motivation"
#   - SCIEFF  → latent factor for "Science Self-Efficacy"
# The operator "=~" means "is measured by".
# For example, MOT is measured by the four motivation items (ST113Q01TA–ST113Q04TA).

fit <- cfa(model, data = pisa_data, estimator = "ULS", ordered = colnames(pisa_data))
# Fit the Confirmatory Factor Analysis model to the data using the 'cfa()' function.
# Arguments:
#   model      → the model you just defined above.
#   data       → 'pisa_data' (the dataset passed from Python to R earlier).
#   estimator  → "ULS" (Unweighted Least Squares), suitable for ordinal Likert-type data.
#   ordered    → specifies that all columns are ordinal variables (Likert responses).

summary(fit, fit.measures = TRUE, standardized = TRUE)
# Display a detailed summary of the CFA results, including:
#   - Overall model fit indices (e.g., CFI, TLI, RMSEA, SRMR)
#   - Factor loadings (standardized)
#   - Variances and covariances
#   - Thresholds for ordered items
# 'fit.measures = TRUE' requests model fit statistics.
# 'standardized = TRUE' reports standardized loadings and variances.
''')

R callback write-console: This is lavaan 0.6-20
lavaan is FREE software! Please report any bugs.

<rpy2.robjects.vectors.ListVector object at 0x00000235CB05A1D0> [19]
R classes: ('lavaan.summary', 'list')
[ListS..., ListS..., ListS..., ListS..., Float..., ListS...]
  header: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB030110> [19]
  optim: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB030750> [19]
  data: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB020CD0> [19]
  test: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB020E90> [19]
  fit: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CB020610> [14]
  pe: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB020A90> [19]

In [38]:
ro.r('''
sink("lavaan_output.txt")
# Redirects all R console output to a text file instead of printing on screen.
# 'sink()' in R is similar to file redirection — it captures any subsequent printed output.

print(summary(fit, fit.measures=TRUE, standardized=TRUE))
# Prints the detailed CFA summary from lavaan, including:
#   • Model fit indices (χ², CFI, TLI, RMSEA, SRMR)
#   • Standardized factor loadings
#   • Variances, covariances, and thresholds
# The 'print()' here ensures the summary text is sent through the R console (and hence captured by sink).

sink()
# Closes the sink — stops redirecting output to the file.
# After this, R console output will again go to the normal console.
''')

# Now read it back in Python
with open("lavaan_output.txt", "r", encoding="utf-8") as f:
    print(f.read())

lavaan 0.6-20 ended normally after 27 iterations

  Estimator                                        ULS
  Optimization method                           NLMINB
  Number of model parameters                        49

  Number of observations                          4895

Model Test User Model:

  Test statistic                               435.703
  Degrees of freedom                                53
  P-value (Unknown)                                 NA

Model Test Baseline Model:

  Test statistic                             84045.342
  Degrees of freedom                                66
  P-value                                           NA

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.995
  Tucker-Lewis Index (TLI)                       0.994

Root Mean Square Error of Approximation:

  RMSEA                                          0.038
  90 Percent confidence interval - lower         0.035
  90 Percent confidence interval - upper         0.042
  P-value H_0: RMSEA <= 0.050                    1.000
  P-value H_0: RMSEA >= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.034

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model        Unstructured

Latent Variables:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT =~
    ST113Q01TA        1.000                               0.892    0.892
    ST113Q02TA        1.064    0.016   66.711    0.000    0.948    0.948
    ST113Q03TA        1.028    0.015   66.494    0.000    0.916    0.916
    ST113Q04TA        0.969    0.015   65.915    0.000    0.864    0.864
  SCIEFF =~
    ST129Q01TA        1.000                               0.743    0.743
    ST129Q02TA        1.085    0.014   78.614    0.000    0.806    0.806
    ST129Q03TA        1.069    0.014   78.223    0.000    0.794    0.794
    ST129Q04TA        1.116    0.014   79.313    0.000    0.829    0.829
    ST129Q05TA        1.127    0.014   79.534    0.000    0.837    0.837
    ST129Q06TA        1.112    0.014   79.224    0.000    0.826    0.826
    ST129Q07TA        0.970    0.013   75.526    0.000    0.720    0.720
    ST129Q08TA        1.080    0.014   78.483    0.000    0.802    0.802

Covariances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT ~~
    SCIEFF            0.221    0.004   60.415    0.000    0.334    0.334

Thresholds:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
    ST113Q01TA|t1    -0.534    0.014  -37.366    0.000   -0.534   -0.534
    ST113Q01TA|t2     0.881    0.014   61.629    0.000    0.881    0.881
    ST113Q01TA|t3     1.608    0.014  112.481    0.000    1.608    1.608
    ST113Q02TA|t1    -0.632    0.014  -44.203    0.000   -0.632   -0.632
    ST113Q02TA|t2     0.829    0.014   58.014    0.000    0.829    0.829
    ST113Q02TA|t3     1.644    0.014  115.035    0.000    1.644    1.644
    ST113Q03TA|t1    -0.597    0.014  -41.780    0.000   -0.597   -0.597
    ST113Q03TA|t2     0.704    0.014   49.264    0.000    0.704    0.704
    ST113Q03TA|t3     1.539    0.014  107.665    0.000    1.539    1.539
    ST113Q04TA|t1    -0.676    0.014  -47.264    0.000   -0.676   -0.676
    ST113Q04TA|t2     0.582    0.014   40.714    0.000    0.582    0.582
    ST113Q04TA|t3     1.403    0.014   98.160    0.000    1.403    1.403
    ST129Q01TA|t1    -0.594    0.014  -41.566    0.000   -0.594   -0.594
    ST129Q01TA|t2     0.906    0.014   63.391    0.000    0.906    0.906
    ST129Q01TA|t3     1.518    0.014  106.168    0.000    1.518    1.518
    ST129Q02TA|t1    -0.545    0.014  -38.111    0.000   -0.545   -0.545
    ST129Q02TA|t2     0.882    0.014   61.734    0.000    0.882    0.882
    ST129Q02TA|t3     1.584    0.014  110.817    0.000    1.584    1.584
    ST129Q03TA|t1    -0.663    0.014  -46.412    0.000   -0.663   -0.663
    ST129Q03TA|t2     0.604    0.014   42.252    0.000    0.604    0.604
    ST129Q03TA|t3     1.376    0.014   96.279    0.000    1.376    1.376
    ST129Q04TA|t1    -0.642    0.014  -44.905    0.000   -0.642   -0.642
    ST129Q04TA|t2     0.715    0.014   50.001    0.000    0.715    0.715
    ST129Q04TA|t3     1.459    0.014  102.049    0.000    1.459    1.459
    ST129Q05TA|t1    -0.621    0.014  -43.419    0.000   -0.621   -0.621
    ST129Q05TA|t2     0.691    0.014   48.350    0.000    0.691    0.691
    ST129Q05TA|t3     1.494    0.014  104.499    0.000    1.494    1.494
    ST129Q06TA|t1    -0.680    0.014  -47.580    0.000   -0.680   -0.680
    ST129Q06TA|t2     0.610    0.014   42.683    0.000    0.610    0.610
    ST129Q06TA|t3     1.414    0.014   98.933    0.000    1.414    1.414
    ST129Q07TA|t1    -0.784    0.014  -54.840    0.000   -0.784   -0.784
    ST129Q07TA|t2     0.413    0.014   28.905    0.000    0.413    0.413
    ST129Q07TA|t3     1.153    0.014   80.675    0.000    1.153    1.153
    ST129Q08TA|t1    -0.577    0.014  -40.333    0.000   -0.577   -0.577
    ST129Q08TA|t2     0.631    0.014   44.116    0.000    0.631    0.631
    ST129Q08TA|t3     1.350    0.014   94.464    0.000    1.350    1.350

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
   .ST113Q01TA        0.205                               0.205    0.205
   .ST113Q02TA        0.101                               0.101    0.101
   .ST113Q03TA        0.160                               0.160    0.160
   .ST113Q04TA        0.253                               0.253    0.253
   .ST129Q01TA        0.449                               0.449    0.449
   .ST129Q02TA        0.350                               0.350    0.350
   .ST129Q03TA        0.370                               0.370    0.370
   .ST129Q04TA        0.313                               0.313    0.313
   .ST129Q05TA        0.300                               0.300    0.300
   .ST129Q06TA        0.318                               0.318    0.318
   .ST129Q07TA        0.481                               0.481    0.481
   .ST129Q08TA        0.357                               0.357    0.357
    MOT               0.795    0.016   50.234    0.000    1.000    1.000
    SCIEFF            0.551    0.010   55.587    0.000    1.000    1.000

In [39]:
ro.r('''
library(lavaan)

# Multi-group CFA: test configural invariance first
configural_model <- '
  MOT =~ ST113Q01TA + ST113Q02TA + ST113Q03TA + ST113Q04TA
  SCIEFF =~ ST129Q01TA + ST129Q02TA + ST129Q03TA + ST129Q04TA +
             ST129Q05TA + ST129Q06TA + ST129Q07TA + ST129Q08TA
'

# Fit the model separately across gender groups
configural_fit <- cfa(configural_model, data = pisa_data,
                      estimator = "ULS",
                      ordered = colnames(pisa_data),
                      group = "ST004D01T")   # gender variable

summary(configural_fit, fit.measures = TRUE, standardized = TRUE)
''')

<rpy2.robjects.vectors.ListVector object at 0x00000235CB01F610> [19]
R classes: ('lavaan.summary', 'list')
[ListS..., ListS..., ListS..., ListS..., Float..., ListS...]
  header: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB003F50> [19]
  optim: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB001050> [19]
  data: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB0008D0> [19]
  test: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB003F50> [19]
  fit: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CB001050> [14]
  pe: <class 'rpy2.rinterface.ListSexpVector'>
  <rpy2.rinterface.ListSexpVector object at 0x00000235CB003F50> [19]

In [42]:
ro.r('''
sink("configural_output.txt")
print(summary(configural_fit, fit.measures = TRUE, standardized = TRUE))
sink()
''')

# Read the saved output back into Python
with open("configural_output.txt", "r", encoding="utf-8") as f:
    print(f.read())

lavaan 0.6-20 ended normally after 34 iterations

  Estimator                                        ULS
  Optimization method                           NLMINB
  Number of model parameters                        98

  Number of observations per group:
    1                                             2492
    2                                             2403

Model Test User Model:

  Test statistic                               465.028
  Degrees of freedom                               106
  P-value (Unknown)                                 NA
  Test statistic for each group:
    1                                          213.995
    2                                          251.033

Model Test Baseline Model:

  Test statistic                             84016.959
  Degrees of freedom                               132
  P-value                                           NA

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.996
  Tucker-Lewis Index (TLI)                       0.995

Root Mean Square Error of Approximation:

  RMSEA                                          0.037
  90 Percent confidence interval - lower         0.034
  90 Percent confidence interval - upper         0.041
  P-value H_0: RMSEA <= 0.050                    1.000
  P-value H_0: RMSEA >= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.035

Parameter Estimates:

  Parameterization                               Delta
  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model        Unstructured


Group 1 [1]:

Latent Variables:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT =~
    ST113Q01TA        1.000                               0.902    0.902
    ST113Q02TA        1.059    0.023   46.126    0.000    0.955    0.955
    ST113Q03TA        1.015    0.022   46.007    0.000    0.916    0.916
    ST113Q04TA        0.933    0.021   45.466    0.000    0.842    0.842
  SCIEFF =~
    ST129Q01TA        1.000                               0.724    0.724
    ST129Q02TA        1.071    0.020   53.263    0.000    0.775    0.775
    ST129Q03TA        1.068    0.020   53.223    0.000    0.774    0.774
    ST129Q04TA        1.116    0.021   53.972    0.000    0.808    0.808
    ST129Q05TA        1.132    0.021   54.203    0.000    0.819    0.819
    ST129Q06TA        1.137    0.021   54.273    0.000    0.823    0.823
    ST129Q07TA        0.990    0.019   51.789    0.000    0.717    0.717
    ST129Q08TA        1.121    0.021   54.044    0.000    0.811    0.811

Covariances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT ~~
    SCIEFF            0.195    0.005   39.962    0.000    0.298    0.298

Thresholds:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
    ST113Q01TA|t1    -0.470    0.020  -23.479    0.000   -0.470   -0.470
    ST113Q01TA|t2     1.002    0.020   50.023    0.000    1.002    1.002
    ST113Q01TA|t3     1.713    0.020   85.505    0.000    1.713    1.713
    ST113Q02TA|t1    -0.531    0.020  -26.496    0.000   -0.531   -0.531
    ST113Q02TA|t2     0.944    0.020   47.121    0.000    0.944    0.944
    ST113Q02TA|t3     1.722    0.020   85.944    0.000    1.722    1.722
    ST113Q03TA|t1    -0.495    0.020  -24.721    0.000   -0.495   -0.495
    ST113Q03TA|t2     0.783    0.020   39.100    0.000    0.783    0.783
    ST113Q03TA|t3     1.602    0.020   79.957    0.000    1.602    1.602
    ST113Q04TA|t1    -0.598    0.020  -29.852    0.000   -0.598   -0.598
    ST113Q04TA|t2     0.625    0.020   31.184    0.000    0.625    0.625
    ST113Q04TA|t3     1.492    0.020   74.478    0.000    1.492    1.492
    ST129Q01TA|t1    -0.579    0.020  -28.897    0.000   -0.579   -0.579
    ST129Q01TA|t2     0.962    0.020   47.991    0.000    0.962    0.962
    ST129Q01TA|t3     1.543    0.020   77.019    0.000    1.543    1.543
    ST129Q02TA|t1    -0.478    0.020  -23.873    0.000   -0.478   -0.478
    ST129Q02TA|t2     0.950    0.020   47.436    0.000    0.950    0.950
    ST129Q02TA|t3     1.624    0.020   81.063    0.000    1.624    1.624
    ST129Q03TA|t1    -0.580    0.020  -28.956    0.000   -0.580   -0.580
    ST129Q03TA|t2     0.672    0.020   33.538    0.000    0.672    0.672
    ST129Q03TA|t3     1.377    0.020   68.721    0.000    1.377    1.377
    ST129Q04TA|t1    -0.572    0.020  -28.541    0.000   -0.572   -0.572
    ST129Q04TA|t2     0.763    0.020   38.084    0.000    0.763    0.763
    ST129Q04TA|t3     1.489    0.020   74.325    0.000    1.489    1.489
    ST129Q05TA|t1    -0.526    0.020  -26.265    0.000   -0.526   -0.526
    ST129Q05TA|t2     0.748    0.020   37.350    0.000    0.748    0.748
    ST129Q05TA|t3     1.489    0.020   74.325    0.000    1.489    1.489
    ST129Q06TA|t1    -0.627    0.020  -31.306    0.000   -0.627   -0.627
    ST129Q06TA|t2     0.644    0.020   32.166    0.000    0.644    0.644
    ST129Q06TA|t3     1.403    0.020   70.041    0.000    1.403    1.403
    ST129Q07TA|t1    -0.790    0.020  -39.442    0.000   -0.790   -0.790
    ST129Q07TA|t2     0.371    0.020   18.541    0.000    0.371    0.371
    ST129Q07TA|t3     1.068    0.020   53.282    0.000    1.068    1.068
    ST129Q08TA|t1    -0.490    0.020  -24.437    0.000   -0.490   -0.490
    ST129Q08TA|t2     0.691    0.020   34.488    0.000    0.691    0.691
    ST129Q08TA|t3     1.362    0.020   67.952    0.000    1.362    1.362

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
   .ST113Q01TA        0.186                               0.186    0.186
   .ST113Q02TA        0.088                               0.088    0.088
   .ST113Q03TA        0.161                               0.161    0.161
   .ST113Q04TA        0.291                               0.291    0.291
   .ST129Q01TA        0.476                               0.476    0.476
   .ST129Q02TA        0.399                               0.399    0.399
   .ST129Q03TA        0.402                               0.402    0.402
   .ST129Q04TA        0.347                               0.347    0.347
   .ST129Q05TA        0.329                               0.329    0.329
   .ST129Q06TA        0.323                               0.323    0.323
   .ST129Q07TA        0.487                               0.487    0.487
   .ST129Q08TA        0.342                               0.342    0.342
    MOT               0.814    0.023   35.072    0.000    1.000    1.000
    SCIEFF            0.524    0.014   37.820    0.000    1.000    1.000


Group 2 [2]:

Latent Variables:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT =~
    ST113Q01TA        1.000                               0.878    0.878
    ST113Q02TA        1.069    0.022   47.913    0.000    0.939    0.939
    ST113Q03TA        1.045    0.022   47.784    0.000    0.918    0.918
    ST113Q04TA        1.010    0.021   47.532    0.000    0.887    0.887
  SCIEFF =~
    ST129Q01TA        1.000                               0.760    0.760
    ST129Q02TA        1.097    0.019   57.751    0.000    0.833    0.833
    ST129Q03TA        1.068    0.019   57.248    0.000    0.811    0.811
    ST129Q04TA        1.117    0.019   58.077    0.000    0.848    0.848
    ST129Q05TA        1.123    0.019   58.179    0.000    0.853    0.853
    ST129Q06TA        1.092    0.019   57.666    0.000    0.829    0.829
    ST129Q07TA        0.972    0.018   55.340    0.000    0.738    0.738
    ST129Q08TA        1.041    0.018   56.762    0.000    0.791    0.791

Covariances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
  MOT ~~
    SCIEFF            0.242    0.005   44.767    0.000    0.363    0.363

Thresholds:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
    ST113Q01TA|t1    -0.603    0.020  -29.531    0.000   -0.603   -0.603
    ST113Q01TA|t2     0.768    0.020   37.616    0.000    0.768    0.768
    ST113Q01TA|t3     1.515    0.020   74.238    0.000    1.515    1.515
    ST113Q02TA|t1    -0.744    0.020  -36.459    0.000   -0.744   -0.744
    ST113Q02TA|t2     0.721    0.020   35.323    0.000    0.721    0.721
    ST113Q02TA|t3     1.573    0.020   77.100    0.000    1.573    1.573
    ST113Q03TA|t1    -0.710    0.020  -34.795    0.000   -0.710   -0.710
    ST113Q03TA|t2     0.626    0.020   30.704    0.000    0.626    0.626
    ST113Q03TA|t3     1.480    0.020   72.513    0.000    1.480    1.480
    ST113Q04TA|t1    -0.761    0.020  -37.274    0.000   -0.761   -0.761
    ST113Q04TA|t2     0.539    0.020   26.402    0.000    0.539    0.539
    ST113Q04TA|t3     1.321    0.020   64.753    0.000    1.321    1.321
    ST129Q01TA|t1    -0.610    0.020  -29.899    0.000   -0.610   -0.610
    ST129Q01TA|t2     0.851    0.020   41.731    0.000    0.851    0.851
    ST129Q01TA|t3     1.492    0.020   73.130    0.000    1.492    1.492
    ST129Q02TA|t1    -0.616    0.020  -30.208    0.000   -0.616   -0.616
    ST129Q02TA|t2     0.816    0.020   39.994    0.000    0.816    0.816
    ST129Q02TA|t3     1.545    0.020   75.721    0.000    1.545    1.545
    ST129Q03TA|t1    -0.755    0.020  -37.001    0.000   -0.755   -0.755
    ST129Q03TA|t2     0.536    0.020   26.284    0.000    0.536    0.536
    ST129Q03TA|t3     1.376    0.020   67.417    0.000    1.376    1.376
    ST129Q04TA|t1    -0.718    0.020  -35.191    0.000   -0.718   -0.718
    ST129Q04TA|t2     0.666    0.020   32.657    0.000    0.666    0.666
    ST129Q04TA|t3     1.429    0.020   70.012    0.000    1.429    1.429
    ST129Q05TA|t1    -0.725    0.020  -35.522    0.000   -0.725   -0.725
    ST129Q05TA|t2     0.634    0.020   31.078    0.000    0.634    0.634
    ST129Q05TA|t3     1.499    0.020   73.443    0.000    1.499    1.499
    ST129Q06TA|t1    -0.737    0.020  -36.123    0.000   -0.737   -0.737
    ST129Q06TA|t2     0.575    0.020   28.193    0.000    0.575    0.575
    ST129Q06TA|t3     1.426    0.020   69.871    0.000    1.426    1.426
    ST129Q07TA|t1    -0.777    0.020  -38.098    0.000   -0.777   -0.777
    ST129Q07TA|t2     0.457    0.020   22.408    0.000    0.457    0.457
    ST129Q07TA|t3     1.252    0.020   61.361    0.000    1.252    1.252
    ST129Q08TA|t1    -0.672    0.020  -32.913    0.000   -0.672   -0.672
    ST129Q08TA|t2     0.570    0.020   27.952    0.000    0.570    0.570
    ST129Q08TA|t3     1.339    0.020   65.619    0.000    1.339    1.339

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all
   .ST113Q01TA        0.228                               0.228    0.228
   .ST113Q02TA        0.119                               0.119    0.119
   .ST113Q03TA        0.157                               0.157    0.157
   .ST113Q04TA        0.213                               0.213    0.213
   .ST129Q01TA        0.423                               0.423    0.423
   .ST129Q02TA        0.306                               0.306    0.306
   .ST129Q03TA        0.342                               0.342    0.342
   .ST129Q04TA        0.280                               0.280    0.280
   .ST129Q05TA        0.272                               0.272    0.272
   .ST129Q06TA        0.312                               0.312    0.312
   .ST129Q07TA        0.455                               0.455    0.455
   .ST129Q08TA        0.374                               0.374    0.374
    MOT               0.772    0.022   35.736    0.000    1.000    1.000
    SCIEFF            0.577    0.014   40.707    0.000    1.000    1.000

In [ ]:
ro.r('''
metric_fit <- cfa(configural_model,
                  data = pisa_data,
                  estimator = "ULS",
                  ordered = colnames(pisa_data),
                  group = "ST004D01T",
                  group.equal = "loadings")

sink("metric_output.txt")
print(summary(metric_fit, fit.measures = TRUE, standardized = TRUE))
sink()
''')

# Optional: quickly check key indices
metric_indices = ro.r('fitMeasures(metric_fit, c("cfi","tli","rmsea","srmr"))')
print(dict(zip(metric_indices.names, list(metric_indices))))

{'cfi': 0.9955059006275455, 'tli': 0.9948860248520346, 'rmsea': 0.03644699938236917, 'srmr': 0.035903802691590256}

In [45]:
ro.r('anova(configural_fit, metric_fit)')

<rpy2.robjects.vectors.DataFrame object at 0x00000235CB0318D0> [19]
R classes: ('anova', 'data.frame')
[Int..., Boo..., Boo..., Flo..., Flo..., Flo..., Int..., Flo...]
  Df: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x00000235CAFB2D90> [13]
  AIC: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x00000235CAFB2050> [10]
  BIC: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x00000235CAFB3050> [10]
  Chisq: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFB0E10> [14]
  Chisq diff: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFB2050> [14]
  RMSEA: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFB2FD0> [14]
  Df diff: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x00000235CAFB1D90> [13]
  Pr(>Chisq): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFB2210> [14]

In [46]:
ro.r('''
scalar_fit <- cfa(configural_model,
                  data = pisa_data,
                  estimator = "ULS",
                  ordered = colnames(pisa_data),
                  group = "ST004D01T",
                  group.equal = c("loadings", "intercepts"))

# Save and inspect summary
sink("scalar_output.txt")
print(summary(scalar_fit, fit.measures = TRUE, standardized = TRUE))
sink()

# Extract fit measures
scalar_indices <- fitMeasures(scalar_fit, c("cfi","tli","rmsea","srmr"))
print(scalar_indices)

# Compare all three models
anova(configural_fit, metric_fit, scalar_fit)
''')

  cfi   tli rmsea  srmr
0.995 0.995 0.037 0.036

R callback write-console: In addition:
R callback write-console: Warning message:

R callback write-console: lavaan->lav_model_vcov():
   The variance-covariance matrix of the estimated parameters (vcov) does not
   appear to be positive definite! The smallest eigenvalue (= 4.195919e-19)
   is close to zero. This may be a symptom that the model is not identified.

<rpy2.robjects.vectors.DataFrame object at 0x00000235CB044310> [19]
R classes: ('anova', 'data.frame')
[Int..., Boo..., Boo..., Flo..., Flo..., Flo..., Int..., Flo...]
  Df: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x00000235CAFD3210> [13]
  AIC: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x00000235CAFD3D50> [10]
  BIC: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x00000235CAFD0F50> [10]
  Chisq: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFD0B90> [14]
  Chisq diff: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFD3D50> [14]
  RMSEA: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAFD2910> [14]
  Df diff: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x00000235CAFD0450> [13]
  Pr(>Chisq): <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x00000235CAF88F90> [14]

In [47]:
ro.r('''
latent_mean_fit <- cfa(configural_model,
                       data = pisa_data,
                       estimator = "ULS",
                       ordered = colnames(pisa_data),
                       group = "ST004D01T",
                       group.equal = c("loadings", "intercepts"),
                       group.partial = NULL)

# Extract latent means for group 2 (females)
parameterEstimates(latent_mean_fit, standardized = TRUE)[parameterEstimates(latent_mean_fit)$lhs %in% c("MOT","SCIEFF") & parameterEstimates(latent_mean_fit)$op == "~1", ]
''')

R callback write-console: In addition:
R callback write-console: Warning message:

R callback write-console: lavaan->lav_model_vcov():
   The variance-covariance matrix of the estimated parameters (vcov) does not
   appear to be positive definite! The smallest eigenvalue (= 4.195919e-19)
   is close to zero. This may be a symptom that the model is not identified.

<rpy2.robjects.vectors.DataFrame object at 0x00000235CB001410> [19]
R classes: ('lavaan.data.frame', 'data.frame')
[StrSexpVe..., StrSexpVe..., StrSexpVe..., IntSexpVe..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  lhs: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x00000235CAF8B7D0> [16]
R classes: ('character',)
['MOT', 'SCIEFF', 'MOT', 'SCIEFF']
  op: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x00000235CAFE2C50> [16]
R classes: ('character',)
['~1', '~1', '~1', '~1']
  rhs: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x00000235CAFE2350> [16]
R classes: ('character',)
['', '', '', '']
  block: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x00000235CAF82FD0> [13]
R classes: ('integer',)
[1, 1, 2, 2]
...
  label: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x00000235CAF82F10> [14]
R classes: ('numeric',)
[0.000000, 0.000000, -0.010501, -0.007348]
  est: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x00000235CAF81390> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.010501, 0.007348]
  se: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x00000235CAF80B10> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000]
  z: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x00000235CAF81750> [14]
R classes: ('numeric',)
[0.000000, 0.000000, 0.000000, 0.000000]

In [48]:
ro.r('''
full_params <- parameterEstimates(latent_mean_fit,
                                  standardized = TRUE,
                                  ci = TRUE)
write.csv(full_params, "latent_means_full.csv", row.names = FALSE)
''')

import pandas as pd
df = pd.read_csv("latent_means_full.csv")
print(df.head(20))

           lhs  op         rhs  block  group  label       est        se  \
0          MOT  =~  ST113Q01TA      1      1    NaN  1.000000  0.000000
1          MOT  =~  ST113Q02TA      1      1   .p2.  1.063816  0.015988
2          MOT  =~  ST113Q03TA      1      1   .p3.  1.031086  0.015542
3          MOT  =~  ST113Q04TA      1      1   .p4.  0.972677  0.014788
4       SCIEFF  =~  ST129Q01TA      1      1    NaN  1.000000  0.000000
5       SCIEFF  =~  ST129Q02TA      1      1   .p6.  1.084506  0.013807
6       SCIEFF  =~  ST129Q03TA      1      1   .p7.  1.067957  0.013665
7       SCIEFF  =~  ST129Q04TA      1      1   .p8.  1.116390  0.014084
8       SCIEFF  =~  ST129Q05TA      1      1   .p9.  1.127166  0.014178
9       SCIEFF  =~  ST129Q06TA      1      1  .p10.  1.112665  0.014051
10      SCIEFF  =~  ST129Q07TA      1      1  .p11.  0.980171  0.012934
11      SCIEFF  =~  ST129Q08TA      1      1  .p12.  1.078178  0.013753
12  ST113Q01TA   |          t1      1      1    NaN -0.470439  0.020036
13  ST113Q01TA   |          t2      1      1    NaN  1.002273  0.020036
14  ST113Q01TA   |          t3      1      1    NaN  1.713191  0.020036
15  ST113Q02TA   |          t1      1      1    NaN -0.530875  0.020036
16  ST113Q02TA   |          t2      1      1    NaN  0.944128  0.020036
17  ST113Q02TA   |          t3      1      1    NaN  1.721985  0.020036
18  ST113Q03TA   |          t1      1      1    NaN -0.495304  0.020036
19  ST113Q03TA   |          t2      1      1    NaN  0.783409  0.020036

            z  pvalue  ci.lower  ci.upper    std.lv   std.all
0         NaN     NaN  1.000000  1.000000  0.888790  0.888790
1   66.538369     0.0  1.032480  1.095152  0.945509  0.945509
2   66.342637     0.0  1.000625  1.061548  0.916419  0.916419
3   65.776528     0.0  0.943694  1.001660  0.864505  0.864505
4         NaN     NaN  1.000000  1.000000  0.729677  0.729677
5   78.548122     0.0  1.057445  1.111567  0.791339  0.791339
6   78.151943     0.0  1.041174  1.094740  0.779263  0.779263
7   79.269156     0.0  1.088787  1.143994  0.814604  0.814604
8   79.500629     0.0  1.099377  1.154954  0.822467  0.822467
9   79.187710     0.0  1.085125  1.140204  0.811886  0.811886
10  75.781639     0.0  0.954821  1.005521  0.715208  0.715208
11  78.398432     0.0  1.051224  1.105133  0.786721  0.786721
12 -23.479464     0.0 -0.509709 -0.431168 -0.470439 -0.470439
13  50.023169     0.0  0.963003  1.041543  1.002273  1.002273
14  85.504922     0.0  1.673921  1.752461  1.713191  1.713191
15 -26.495816     0.0 -0.570145 -0.491605 -0.530875 -0.530875
16  47.121171     0.0  0.904858  0.983398  0.944128  0.944128
17  85.943819     0.0  1.682715  1.761255  1.721985  1.721985
18 -24.720515     0.0 -0.534575 -0.456034 -0.495304 -0.495304
19  39.099748     0.0  0.744139  0.822679  0.783409  0.783409

Measurement Invariance and Latent Mean Comparison

A series of multi-group confirmatory factor analyses (MCFA) were conducted using the lavaan package in R to examine the measurement invariance of the two-factor model of Science Motivation (MOT) and Science Self-Efficacy (SCIEFF) across gender in the PISA 2015 Turkey sample (N = 4,895). The configural model demonstrated excellent fit to the data, χ²(106) = 465.03, CFI = 0.996, TLI = 0.995, RMSEA = 0.037 (90% CI = [0.034, 0.041]), SRMR = 0.035, supporting the same factorial structure across male and female students. Constraining the factor loadings to equality (metric invariance) resulted in a negligible change in fit indices (ΔCFI = 0.0005, ΔRMSEA = 0.001), indicating that the strength of the relationships between items and their respective latent constructs was equivalent across groups. Similarly, constraining both factor loadings and intercepts (scalar invariance) yielded an equally strong fit (CFI = 0.995, TLI = 0.995, RMSEA = 0.037, SRMR = 0.036; ΔCFI < 0.001, ΔRMSEA = 0.001), confirming full scalar invariance across gender.

Given scalar invariance, latent mean comparisons were conducted by fixing the male group’s means to zero and estimating female latent means relative to this baseline. The results indicated trivial and nonsignificant mean differences for both constructs (MOT = 0.011, SCIEFF = 0.007), suggesting that male and female students exhibited comparable levels of science motivation and self-efficacy. Overall, these results confirm that the two-factor structure of science motivation and self-efficacy is psychometrically stable and invariant across gender within the Turkish PISA 2015 dataset.

In [49]:
# Filter standardized loadings for each factor
mot_loadings = df[(df['lhs'] == 'MOT') & (df['op'] == '=~')]['std.all'].astype(float)
scieff_loadings = df[(df['lhs'] == 'SCIEFF') & (df['op'] == '=~')]['std.all'].astype(float)

def compute_cr_ave(loadings):
    # Compute error variances
    error_var = 1 - loadings**2
    # Composite Reliability (CR)
    cr = (loadings.sum()**2) / ((loadings.sum()**2) + error_var.sum())
    # Average Variance Extracted (AVE)
    ave = (loadings**2).sum() / ((loadings**2).sum() + error_var.sum())
    return round(cr, 3), round(ave, 3)

mot_cr, mot_ave = compute_cr_ave(mot_loadings)
scieff_cr, scieff_ave = compute_cr_ave(scieff_loadings)

results = pd.DataFrame({
    "Construct": ["MOT", "SCIEFF"],
    "Composite Reliability (CR)": [mot_cr, scieff_cr],
    "Average Variance Extracted (AVE)": [mot_ave, scieff_ave]
})

print(results)

  Construct  Composite Reliability (CR)  Average Variance Extracted (AVE)
0       MOT                       0.973                             0.819
1    SCIEFF                       0.965                             0.633